### ISSUE TITLE
Documentation for start and end option

### ISSUE THREAD

**Issue by kstamps** [john-mantas/postcss-template-variables#1]
I had to change the options from start/end to open/close. Maybe the readme is incorrect?

```
      template: {
        start: '{{',
        end: '}}'
      }
```

to:

```
      template: {
        open: '{{',
        close: '}}'
      }
```

**Comment by john-mantas** [comment]
Yes, you're right, the readme was incorrect and the correct options are open/close.
Thanks for the heads up, i have fixed the readme file! :)
